
on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: "Environment to deploy"

env:
  REGION: europe-west1

jobs:
  deploy_to_dev:
    uses: ./.github/workflows/p2p.yaml
    with:
      deploy-env: ${{ inputs.deploy_env }}
