
on:
  workflow_dispatch: null
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  fastfeedback:
    uses: ./.github/workflows/p2p-workflow-definition.yaml
  extendedtests:
    uses: ./.github/workflows/p2p-workflow-definition.yaml
  prod:
    uses: ./.github/workflows/p2p-workflow-definition.yaml