
on:
  workflow_dispatch: null
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:

  version:
    runs-on: ubuntu-latest
    env:
      USE_SEMVER_AS_IMAGE_TAG: true
      FOO: ${{ var.STAGE_DEV }}
    steps:
      - name: Get version
        id: version
        shell: bash
        run: |
          echo "STAGE_DEV=$STAGE_DEV"


#  fastfeedback:
#    uses: ./.github/workflows/p2p-workflow-definition.yaml
#  extendedtests:
#    uses: ./.github/workflows/p2p-workflow-definition.yaml
#  prod:
#    uses: ./.github/workflows/p2p-workflow-definition.yaml