
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

permissions:
  contents: read
  id-token: write

jobs:
  version:
    runs-on: ubuntu-latest
    env:
      STAGE_DEV: ${{ vars.STAGE_DEV }}
    steps:
      - name: Get version
        shell: bash
        run: |
          echo "STAGE_DEV=$STAGE_DEV"
#  fastfeedback:
#    uses: ./.github/workflows/external-workflow-fastfeedback.yaml
#
#  extendedtests:
#    uses: ./.github/workflows/external-workflow-exttests.yaml
#    needs: [fastfeedback]
#    with:
#      image_tag: ${{ needs.fastfeedback.outputs.image_tag }}
#      semver: ${{ needs.fastfeedback.outputs.semver }}
##  prod:
##    uses: ./.github/workflows/external-workflow-prod.yaml