
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

env:
  REGION: europe-west1

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  p2p:
    uses: ./.github/workflows/p2p.yaml
    strategy:
      matrix:
        deploy_env:
          - cecg-sandbox
          - cecg-sandbox-1
          - cecg-sandbox-2
          - cecg-sandbox-3
    with:
      deploy-env: ${{ matrix.deploy_env }}
