name: This is an example

on:
  pull_request:
   types: [opened, synchronize, labeled, unlabeled]

jobs:
  
  p2p:
    uses: ./.github/workflows/p2p.yaml
    secrets:
      env_vars: |
        ENVIRONMENT=${{ vars.ENV }}
        BASE_URL=${{ vars.BASE_URL }}
    with:
      deploy-env: cecg-sandbox
      env-name: ${{ vars.ENV }}
      project-id: ${{ vars.PROJECT_ID }}
      project-number: ${{ vars.PROJECT_NUMBER }}
      tenant-name: ${{ vars.TENANT_NAME }}
  
  