
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

env:
  REGION: europe-west1

jobs:
  p2p:
    uses: ./.github/workflows/p2p.yaml
    strategy:
      matrix:
        deploy_env:
          - cecg-sandbox
          - cecg-sandbox-1
          - cecg-sandbox-2
          - cecg-sandbox-3
    with:
      deploy-env: ${{ needs.generate_matrix.outputs.deploy_env }}
