
on:
  workflow_dispatch: null

env:
  REGION: europe-west1

jobs:
  deploy_to_dev:
    uses: ./.github/workflows/p2p-workflow-definition.yaml
    secrets:
      env_vars: |
        ENV=${{ vars.ENV }}
        BASE_URL=${{ vars.BASE_URL }}
        TENANT_NAME=${{ vars.TENANT_NAME }}
        PROJECT_ID=${{ vars.PROJECT_ID }}
        PROJECT_NAME=${{ vars.PROJECT_NAME }}
    with:
      deploy-env: 'cecg-sandbox'
