
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]


env:
  REGION: europe-west1

jobs:
  generate_matrix:
    runs-on: ubuntu-latest
    # generate a dynamic matrix
    strategy:

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  p2p:
    uses: ./.github/workflows/p2p.yaml
    strategy:
      matrix: ${{ fromJson(vars.STAGE_DEV) }}
    with:
      deploy-env: ${{ matrix.deploy_env }}
