
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

env:
  REGION: europe-west1

jobs:
  p2p:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deploy_env:
          - cecg-sandbox
          - cecg-sandbox-1
          - cecg-sandbox-2
          - cecg-sandbox-3
    environment: ${{ matrix.deploy_env }}
    outputs:
      deploy_env: ${{ matrix.deploy_env }}
      matrix: ${{ matrix.deploy }}
      project_id: ${{ vars.PROJECT_ID }}
      project_number: ${{ vars.PROJECT_NUMBER }}
      tenant_name: ${{ vars.TENANT_NAME }}
      base_url: ${{ vars.BASE_URL }}
      env: ${{ vars.ENV }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Run P2P
        uses: ./.github/workflows/p2p.yaml
        id: run-p2p
        with:
          deploy-env: ${{ matrix.deploy_env }}
          env-name: ${{ vars.ENV }}
          project-id: ${{ vars.PROJECT_ID }}
          project-number: ${{ vars.PROJECT_NUMBER }}
          tenant-name: ${{ vars.TENANT_NAME }}

