on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      github_env:
        required: false
        type: string
        default: ''


jobs:
  exec:
    name: ${{ inputs.command }}-${{ inputs.github_env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_env }}
    env:
      REGISTRY: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/tenant
      SERVICE_ACCOUNT: p2p-${{ vars.TENANT_NAME }}@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com
      WORKLOAD_IDENTITY_PROVIDER: projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/p2p-${{ vars.TENANT_NAME }}/providers/p2p-${{ vars.TENANT_NAME }}
      BASE_URL: ${{ vars.BASE_URL }}
      ENVIRONMENT: ${{ vars.ENV }}
      ENV: ${{ vars.ENV }}
      PROJECT_NUMBER: ${{ vars.PROJECT_NUMBER }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      TENANT_NAME: ${{ vars.TENANT_NAME }}
      ADDITIONAL_ENV_VARS: "FOO,BAR"
    steps:
      - name: add_additional_env_vars
        env:
          ALL_VARS: ${{ toJSON(vars) }}"
        run: |
          echo "ALL_VARS=$ALL_VARS"
      - name: print
        run: |
          echo "BASE_URL=$BASE_URL"
          echo "PROJECT_ID=$PROJECT_ID"
          echo "REGION=$REGION"
          echo "SERVICE_ACCOUNT=$SERVICE_ACCOUNT"
          echo "WORKLOAD_IDENTITY_PROVIDER=$WORKLOAD_IDENTITY_PROVIDER"
          echo "REGISTRY=$REGISTRY"
          echo "PROJECT_NUMBER=$PROJECT_NUMBER"
          echo "TENANT_NAME=$TENANT_NAME"
          echo "ENV=$ENVIRONMENT"

