name: p2p-command

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
      github_env:
        required: false
        type: string
        default: ''


jobs:
  setup_command:
    name: ${{ inputs.command }}-${{ inputs.github_env }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_env }}
    env:
      REGISTRY: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/tenant
      SERVICE_ACCOUNT: p2p-${{ vars.TENANT_NAME }}@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com
      WORKLOAD_IDENTITY_PROVIDER: projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/p2p-${{ vars.TENANT_NAME }}/providers/p2p-${{ vars.TENANT_NAME }}
      BASE_URL: ${{ vars.BASE_URL }}
      ENVIRONMENT: ${{ vars.ENV }}
      ENV: ${{ vars.ENV }}
      PROJECT_NUMBER: ${{ vars.PROJECT_NUMBER }}
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      TENANT_NAME: ${{ vars.TENANT_NAME }}
    outputs:
      workflow_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ env.SERVICE_ACCOUNT }}
      deploy-env: ${{ inputs.deploy-env }}
      region: ${{ vars.REGION }}
      project-id: ${{ vars.PROJECT_ID }}
      base-url: ${{ vars.BASE_URL }}
      env_vars: ${{ toJSON(env) }}
      env-name: ${{ vars.ENV }}
    steps:
      - name: Setup inputs passed to the reusable workflow
        id: setup
        run: |
          echo "workflow_identity_provider=$WORKLOAD_IDENTITY_PROVIDER"
          echo "service_account=$SERVICE_ACCOUNT"


  execute_command:
    name: ${{ inputs.command }}-${{ inputs.github_env }}
    environment: ${{ inputs.github_env }}
    runs-on: ubuntu-latest
    needs: setup_command

    permissions:
      contents: read
      id-token: write

    env: ${{ fromJSON(needs.setup_command.outputs.env_vars) }}
    #env: ${{ fromJSON(secrets.env_vars) }}
    steps:
      - name: print
        run: |
          echo "BASE_URL=$BASE_URL"
          echo "PROJECT_ID=$PROJECT_ID"
          echo "REGION=$REGION"
          echo "SERVICE_ACCOUNT=$SERVICE_ACCOUNT"
          echo "WORKLOAD_IDENTITY_PROVIDER=$WORKLOAD_IDENTITY_PROVIDER"
          echo "REGISTRY=$REGISTRY"
          echo "PROJECT_NUMBER=$PROJECT_NUMBER"
          echo "TENANT_NAME=$TENANT_NAME"
          echo "ENV=$ENVIRONMENT"

