
on:
  workflow_call:
    secrets:
      env_vars:
        required: false
    inputs:
      stage-prod:
        required: false
        type: string
        default: ${{ vars.STAGE_PROD }}
      dry-run:
        required: false
        type: boolean
        default: false
      tag:
        required: false
        type: string
        default: ''
      semver:
        required: false
        type: string
        default: ''
      pre-targets:
        description: |
          Make targets to run before each p2p command
        required: false
        type: string
        default: ''
      post-targets:
        description: |
          Make targets to run after each p2p command
        required: false
        type: string
        default: ''

jobs:
  prod-deploy:
    name: prod-deploy
    #if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/envmatrix-execute-command.yaml
    with:
      command: p2p-prod
      envmatrix: ${{ inputs.stage-prod }}


