name: Developer Platform P2P


on:
  workflow_dispatch: null
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  build:
    uses: ./.github/workflows/envmatrix-execute-command.yaml
    with:
      command: build
      envmatrix: ${{ vars.STAGE_DEV }}

  functional-test:
    needs: [build]
    uses: ./.github/workflows/envmatrix-execute-command.yaml
    with:
      command: func
      envmatrix: ${{ vars.STAGE_DEV }}


  prod-deploy:
    needs: [build,functional-test]
    uses: ./.github/workflows/envmatrix-execute-command.yaml
    with:
      command: prod
      envmatrix: ${{ vars.STAGE_PROD }}
#
#
#  nft-test:
#    name: nft-test
#    needs: [functional-test, setup]
#    uses: ./.github/workflows/execute-command.yaml
#    with:
#      command: p2p-nft
#      foo: ${{ needs.setup.outputs.env_vars }}
#
#  dev-deploy:
#    name: dev-deploy
#    #if: github.ref == 'refs/heads/main'
#    needs: [nft-test, setup]
#    uses: ./.github/workflows/execute-command.yaml
#    with:
#      command: p2p-dev
#      foo: ${{ needs.setup.outputs.env_vars }}

