name: Developer Platform P2P

on:
  workflow_call:
    secrets:
      env_vars:
        required: false
    inputs:
      deploy-env:
        required: true
        type: string
      env-name:
        required: true
        type: string
      project-id:
        required: true
        type: string
      project-number:
        required: true
        type: string
      tenant-name:
        required: true
        type: string
      region:
        type: string
        default: europe-west1

env:
  REGISTRY: ${{ inputs.region }}-docker.pkg.dev/${{ inputs.project-id }}/tenant
  SERVICE_ACCOUNT: p2p-${{ inputs.tenant-name }}@${{ inputs.project-id }}.iam.gserviceaccount.com
  WORKLOAD_IDENTITY_PROVIDER: projects/${{ inputs.project-number }}/locations/global/workloadIdentityPools/p2p-${{ inputs.tenant-name }}/providers/p2p-${{ inputs.tenant-name }}


jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy-env }}
    outputs:
      workflow_identity_provider: ${{ steps.setup.outputs.workflow_identity_provider }}
      service_account: ${{ steps.setup.outputs.service_account }}
    steps:
      - name: Setup inputs passed to the reusable workflow
        id: setup
        run: |
          echo "workflow_identity_provider=$WORKLOAD_IDENTITY_PROVIDER"
          echo "service_account=$SERVICE_ACCOUNT"
