name: Developer Platform P2P

on:
  workflow_call:
    inputs:
      deploy-env:
        required: true
        type: string



jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy-env }}
    env:
      REGISTRY: ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/tenant
      SERVICE_ACCOUNT: p2p-${{ vars.TENANT_NAME }}@${{ vars.PROJECT_ID }}.iam.gserviceaccount.com
      WORKLOAD_IDENTITY_PROVIDER: projects/${{ vars.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/p2p-${{ vars.TENANT_NAME }}/providers/p2p-${{ vars.TENANT_NAME }}
    outputs:
      workflow_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ vars.SERVICE_ACCOUNT }}
      deploy_env: ${{ inputs.deploy-env }}
      region: ${{ vars.REGION }}
      project_id: ${{ vars.PROJECT_ID }}
      project_number: ${{ vars.PROJECT_NUMBER }}
      tenant_name: ${{ vars.TENANT_NAME }}
      base_url: ${{ vars.BASE_URL }}
      env: ${{ vars.ENV }}

    steps:
      - name: Setup inputs passed to the reusable workflow
        id: setup
        run: |
          echo "workflow_identity_provider=$WORKLOAD_IDENTITY_PROVIDER"
          echo "service_account=$SERVICE_ACCOUNT"

  print:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: print
        id: print
        run: |
          printenv
