

on:
  workflow_dispatch: null
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

env:
  MATRIX: '{ "component": ["rod", "jane", "freddy"] }'


jobs:
  example_run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          printf "${{env.MATRIX }}"
