

on:
  workflow_dispatch: null
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  example_matrix:
    strategy:
      matrix:
        version:
          include:
            - { version: 'rod' }
            - { version: 'jane' }
            - { version: 'freddy' }
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ matrix.version }}"
