

on:
  workflow_dispatch: null
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  example_run:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(vars.STAGE_DEV) }}
    steps:
      - run: |
          echo "${{ matrix.deploy_env }}"
