

on:
  workflow_dispatch: null
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

env:
  MYMATRIX: '{ "include": [{ "deploy": "rod"}, {"deploy": "jane" }] }'


jobs:
  example_run:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(env.MYMATRIX) }}
    steps:
      - run: |
          echo "${{ matrix.deploy }}"
