

on:
  workflow_dispatch: null
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  example_matrix:
    strategy:
      matrix:
        version: [10, 12, 14]
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ matrix.version }}"
