

on:
  workflow_dispatch: null
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - { component: 'rod' }
          - { component: 'jane' }
          - { component: 'freddy' }
    outputs:
      matrix: ${{ toJson(matrix) }}
    steps:
        - run: |
            echo "goo"

  example_run:
    needs: example_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.example_matrix.outputs.matrix) }}
    steps:
      - run: |
          echo "${{ matrix.component }}"
